// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxhqEacHUhLDbGwyMFA6t7tgTElZkrPYs',
    appId: '1:793629951057:web:a11b5d3786b8346b68a470',
    messagingSenderId: '793629951057',
    projectId: 'logintest-5fc1d',
    authDomain: 'logintest-5fc1d.firebaseapp.com',
    storageBucket: 'logintest-5fc1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NUYiXseoOMSu3LWHDbZ589h3eBkPxpI',
    appId: '1:793629951057:android:a67be521ea42cbc168a470',
    messagingSenderId: '793629951057',
    projectId: 'logintest-5fc1d',
    storageBucket: 'logintest-5fc1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk4CXs9Uf6Z-41Xyiupbmxo5CW0B31eFc',
    appId: '1:793629951057:ios:d848ebe8b7ffdcf368a470',
    messagingSenderId: '793629951057',
    projectId: 'logintest-5fc1d',
    storageBucket: 'logintest-5fc1d.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk4CXs9Uf6Z-41Xyiupbmxo5CW0B31eFc',
    appId: '1:793629951057:ios:d848ebe8b7ffdcf368a470',
    messagingSenderId: '793629951057',
    projectId: 'logintest-5fc1d',
    storageBucket: 'logintest-5fc1d.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxhqEacHUhLDbGwyMFA6t7tgTElZkrPYs',
    appId: '1:793629951057:web:8f67aee9ee3ddfec68a470',
    messagingSenderId: '793629951057',
    projectId: 'logintest-5fc1d',
    authDomain: 'logintest-5fc1d.firebaseapp.com',
    storageBucket: 'logintest-5fc1d.firebasestorage.app',
  );

}